  <servlet>
     <servlet-name>ServletDemo1</servlet-name>
     <servlet-class>gacl.servlet.study.ServletDemo1</servlet-class>
   </servlet>
 
   <servlet-mapping>
     <servlet-name>ServletDemo1</servlet-name>
     <url-pattern>/servlet/ServletDemo1</url-pattern>
   </servlet-mapping>
  <servlet-mapping>
     <servlet-name>ServletDemo1</servlet-name>
     <url-pattern>/1.htm</url-pattern>
   </servlet-mapping>
    <servlet-mapping>
     <servlet-name>ServletDemo1</servlet-name>
     <url-pattern>/2.jsp</url-pattern>
   </servlet-mapping>
    <servlet-mapping>
     <servlet-name>ServletDemo1</servlet-name>
     <url-pattern>/3.php</url-pattern>
   </servlet-mapping>
    <servlet-mapping>
     <servlet-name>ServletDemo1</servlet-name>
     <url-pattern>/4.ASPX</url-pattern>
   </servlet-mapping>